name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Cache  💾
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**yarn.lock') }}

      - name: Setup Node 🔧
        uses: actions/setup-node@v2

      - run: npm install
      
      - run: npm install postcss

      - run: npm run deploy

      # Unnecessary if hosted on gh-pages /
      #      - run: mkdir out/assets

      #      - run: mv out/_next/* out/assets

      #      - run: rm -rf out/next/

      #      - run: find ./out -type f -exec sed -i -e 's/\/_next//g' {} \;

      - run: touch out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@a1ea191d508feb8485aceba848389d49f80ca2dc # v4.4.3
        with:
          ACCESS_TOKEN: ${{secrets.DEPLOY_KEY}}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
